googleapis/releasetool

CHANGELOG.md

Release releasetool 0.1.0

---

releasetool/commands/start/nodejs.py

Fixes #1 
Example PR: https://github.com/googleapis/nodejs-vision/pull/107

[WIP] Customize start for Node.js

---

CHANGELOG.md
setup.py

Release releasetool 0.2.0

---

releasetool/commands/start/nodejs.py

fix: node CHANGELOG.md npm link

---

CHANGELOG.md
setup.py

Release releasetool 0.2.1

---

nox.py
releasetool/commands/common.py
releasetool/commands/start/nodejs.py
releasetool/commands/start/python.py
releasetool/commands/tag/nodejs.py
releasetool/commands/tag/python.py
releasetool/commands/tag/python_tool.py
releasetool/git.py
releasetool/github.py

Add support for multiple GitHub remotes and releasing across forks

---

releasetool/main.py
releasetool/update_check.py

Check for updates

---

CHANGELOG.md
setup.py

Release releasetool 0.3.0

---

releasetool/commands/common.py
releasetool/commands/start/nodejs.py
releasetool/commands/start/python.py

Correctly handle multiple possible upstreams and correctly compute the upstream change summary

---

releasetool/main.py

Automatically detect the language.

---

CHANGELOG.md
setup.py

Release releasetool 0.4.0

---

CHANGELOG.md
setup.py

Release releasetool 0.5.0

---

README.md
releasetool/commands/start/ruby.py
releasetool/commands/tag/ruby.py
releasetool/main.py

* Add start and tag commands for Ruby
* Add Ruby section to README

Add support for google-cloud-ruby libraries

---

releasetool/commands/start/java.py
releasetool/commands/start/nodejs.py
releasetool/commands/start/python.py
releasetool/github.py

#38 `Some change (#13)` --> `Some change ([#13](https://github.com/owner/repo/pull/13))`

Add links to pull requests in release log

---

CHANGELOG.md
setup.py

Release releasetool 0.6.0

---

releasetool/main.py

fix: `tag` detects default language

---

releasetool/main.py

Add --version flag

---

CHANGELOG.md
setup.py

Release releasetool 0.7.0

---

CHANGELOG.md
setup.py

Release releasetool 0.8.0

---

releasetool/commands/tag/python_tool.py
setup.py

* "Would you like to go the Kokoro build page?" defaults to yes 
* Commitish is automatically copied to the clipboard

Default to yes for opening build page, copy commitish to clipboard

---

releasetool/commands/tag/nodejs.py

fix(nodejs): change output from PyPI -> npm

---

CHANGELOG.md
setup.py

Release releasetool 0.10.0

---

CHANGELOG.md
setup.py

Release releasetool 2018.10.23

---

CHANGELOG.md
setup.py

Release releasetool 2018.10.25

---

releasetool/commands/start/python_tool.py

Only use calver for python_tools, not python

---

releasetool/git.py

Fixes #90
Just a heads up, I'm not really familiar with Python, so I wasn't able to check whether this Regex change does what I expect.

Allow remotes that don't end in .git

---

CHANGELOG.md
setup.py

Release releasetool 2018.10.31

---

CHANGELOG.md
setup.py

Release releasetool 2018.11.01

---

CHANGELOG.md
setup.py

Release releasetool 2018.11.02

---

CHANGELOG.md
setup.py

Release releasetool 2018.11.02.1

---

CHANGELOG.md
setup.py

Release releasetool 2018.11.05

---

releasetool/commands/common.py
releasetool/commands/tag/java.py
releasetool/commands/tag/nodejs.py
releasetool/commands/tag/python.py
releasetool/commands/tag/python_tool.py
releasetool/commands/tag/ruby.py
releasetool/github.py

Make tag idempotent

---

CHANGELOG.md
setup.py

Release releasetool 2018.11.07

---

CHANGELOG.md
setup.py

Release releasetool 2018.11.07.1

---

CHANGELOG.md
setup.py

Release releasetool 2018.11.07.2

---

releasetool/commands/start/go.py

Go commit msg

---

releasetool/commands/tag/python.py

Preparing Python for Autorelease

Make releasetool tag for Python work in non-interactive mode

---

releasetool/commands/start/nodejs.py

 Don't try to commit samples/package.json if it doesn't exist

---

releasetool/commands/publish_reporter.sh

fix: run releasetool as module

---

CHANGELOG.md
setup.py

Release releasetool 2018.12.10

---

releasetool/commands/tag/java.py

Releasetool tag will trigger the `google-auth-java-library/release/stage` job.

Make releasetool tag trigger release job for google-auth-java-library

---

releasetool/commands/start/ruby.py

* Change changelog bullets from "-" to "*"

format ruby changelog consistently

---

releasetool/commands/tag/ruby.py
releasetool/github.py

* Add delete_branch method
* Add delete_branch step to ruby's tag command

Ruby delete branch

---

releasetool/commands/tag/ruby.py

* Allow for scenarios in which user has deleted branch before autorelease has a chance to

handle errors in delete branch

---

README.md

Update releasetool tag instructions

---

CHANGELOG.md
setup.py

Release releasetool 2019.04.04

---

CHANGELOG.md
setup.py

Release releasetool 2019.05.02

---

releasetool/commands/start/ruby.py
releasetool/git.py

* Update `edit_release_notes()`. 
* Add git log and diff detail to the PR description.
[Example PR produced with these changes](https://github.com/googleapis/google-cloud-ruby/pull/3287)

ruby: Update start create_release_pr()

---

releasetool/commands/tag/ruby.py

fixes https://github.com/googleapis/releasetool/issues/189

fix tagging for google-cloud package

---

releasetool/commands/tag/ruby.py

Fix changelog detection for Ruby.

---

releasetool/commands/start/java.py
releasetool/git.py
releasetool/github.py

Java: detect current working branch to use for release

---

CHANGELOG.md
setup.py

Release releasetool 2019.06.06

---

releasetool/commands/start/java.py

Add prompt for autorelease when creating tag

Java: add prompt for autorelease when creating PR

---

README.md

docs: add section to README about auth

---

CHANGELOG.md
setup.py

Release releasetool 2019.06.14

---

releasetool/github.py

we had broken the API surface for autorelease in the last PR.

fix: continue to accept string token

---

.kokoro/release/common.cfg

Job configs need to match the build configs

chore: add common.cfg file

---

releasetool/commands/tag/nodejs.py

To allow for its unique monorepo release logic, `googleapis` is going to use GitHub Actions to handle release PRs and publication logic.

feat(nodejs): googleapis release is handled by actions

---

.kokoro-autorelease/build.sh
autorelease/__main__.py
autorelease/tag.py
releasetool/commands/common.py
releasetool/commands/tag/java.py

Reverts googleapis/releasetool#300

revert: "refactor(java): delegate tagging to release-please"

---

autorelease/tag.py
releasetool/commands/tag/java.py
tests/commands/tag/test_java.py

Java needs to parse out the tagged version from release-please.

fix(java): fix Kokoro job triggering

---

releasetool/commands/tag/nodejs.py

delegate to release-please for apiary mono-repo.

feat(node): switch to manifest based publication for apiary/repo-automation-bots

---

.github/CODEOWNERS

Adds the additional @googleapis/github-automation owner.

meta: add additional @googleapis/github-automation owner

---

setup.py

fix(deps): lock click to 7.x

---

releasetool/commands/tag/ruby.py

Map release kokoro jobs for a bunch of additional Ruby repos.

feat(ruby): Kokoro job mapping for additional Ruby repos

---

releasetool/commands/tag/ruby.py

* Added googleapis/common-protos-ruby and googleapis/gapic-generator-ruby to the list of Ruby monorepos for which the changelog is expected to be in a subdirectory
* Refactor a bit to make it obvious where to edit Ruby repo lists when new repos are added
* Added a todo for a future edit when the Ruby apiary repo release tasks are normalized

fix(ruby): Identify additional Ruby monorepos

---

requirements.txt
setup.py

Reverts googleapis/releasetool#404
Fixes #408

Revert "chore(deps): update dependency protobuf to v4"

---

releasetool/commands/tag/php.py
tests/test_autorelease_trigger.py

See https://github.com/googleapis/google-cloud-php/pull/5618/files
Add a release trigger for the kokoro job which will generate Cloud RAD documentation for PHP

feat: enable release trigger for cloud rad kokoro job

---

.kokoro/release/release.cfg

This should match our presubmit docker image

build: use python-multi for release

---

releasetool/commands/tag/dotnet.py

feat: Releasetool supports .NET new CI infrastructure

---

.kokoro-autorelease/common.cfg
.kokoro/populate-release-secrets.sh
.kokoro/release/release.cfg
.kokoro/trampoline_release.sh

Update release project to use new Cloud SDK release infrastructure.

ci: update release project

---

.kokoro-autorelease/build.sh
.kokoro-autorelease/tag.sh
.kokoro-autorelease/trigger.sh
.trampolinerc

build: fix release scripts to use trampoline_v2

---

autorelease/tag.py

feat: Support per repo denylist for tagging.

---

autorelease/tag.py
releasetool/commands/tag/dotnet.py

chore: Migrate dotnet-spanner-entity-framework to newest CI
