- releasetool/commands/common.py
- releasetool/commands/start/java.py
- releasetool/commands/tag/java.py
- releasetool/commands/tag/nodejs.py
- releasetool/main.py
The general process for java is:
1. Update the version numbers from x.y.z-SNAPSHOT to the target semantic version (without SNAPSHOT).
2. Create the release branch and PR.
3. Do the maven release (not handled here)
4. Merge the release PR
5. Create the GitHub release
6. Bump the version numbers to the (new release+1)-SNAPSHOT (not handled here)
Java libraries do not maintain a running CHANGELOG.md (can revisit this later) so we put the release notes in the PR body and extract them for the GitHub release.
Example PR: https://github.com/google/google-auth-library-java/pull/179
> Add java release commands

- releasetool/commands/tag/java.py
The java release tag needed to be the vX.Y.Z version, not just X.Y.Z. The release names are also with the "v" prefix.
> Fix java release name, tag, and release notes

- releasetool/commands/start/nodejs.py
- releasetool/filehelpers.py
This also involve changing the displayed `package_name` to the actual NPM scoped-name.
`nodejs-vision` => `@google-cloud/nodejs-vision`
fixes #13
> feat(nodejs): bump package version in samples/package.json as well

- releasetool/commands/tag/nodejs.py
Absolutely love the tagging feature of releasetool - it actually waits for CircleCI to complete the publish. Now my node packages won't get forgotten when the CI failed to complete the publish.
Thanks! @theacodes
> fix(nodejs): tag name is just the version for Node.js

- releasetool/commands/tag/python_tool.py
For python tools, provide the user with a link to the Kokoro release job.
```
> Trigger the Kokoro build with the commitish below to publish to PyPI.
Build:		https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod%3Acloud-devrel%2Fclient-libraries%2Freleasetool%2Frelease
Commitish:	f0ca24dc9956eaed66623ee674efb6958b7856f3
Would you like to go the Kokoro build page? [y/N]: y
\o/ All done!
```
> Add link to Kokoro release job for python tools

- releasetool/commands/start/ruby.py
Re-add edit_release_notes to initialize ctx.release_notes.
[fixes #62]
> Fix Ruby start

- releasetool/commands/tag/go.py
- releasetool/git.py
- releasetool/main.py
Add 'releasetool tag' for Go.
This command is quite different for Go, because GitHub is not the source of truth, and also because a "release" for Go is just tagging the repo.
Rather than mess with the Gerritt API, we work off the local repo, and push the tag at the end.
> tag command for Go

- releasetool/commands/start/go.py
- releasetool/main.py
Implement "releasetool start" for Go.
Handles our current state (no go.mod files). Tested by
creating a release CL.
Also some code for go.mod, relatively untested.
> start command for Go

- releasetool/commands/common.py
- releasetool/commands/start/python.py
- releasetool/git.py
Closes #66 
* Release branch is cut from `master` instead of `origin/master`
* Releasetool checks that `master` is up to date with the upstream master branch.
```
/ Hey, busunkim, let's release some stuff!
> Determining GitHub context.
Origin: busunkim96/google-cloud-python, Upstream: GoogleCloudPlatform/google-cloud-python
> Comparing upstream/master to master.
master is up to date with upstream/master
...
```
```
o/ Hey, busunkim, let's release some stuff!
> Determining GitHub context.
Origin: busunkim96/google-cloud-python, Upstream: GoogleCloudPlatform/google-cloud-python
> Comparing upstream/master to master.
WARNING: master is not up to date with upstream/master
> Would you like to continue? [y/N]: y
...
```
> Cut release branch from master, warn when master != upstream/master.

- releasetool/commands/start/java.py
Java publishes packages together and different artifacts are versioned independently. We already have precedent in google-cloud-java to manage all versions in a `versions.txt` file at the root directory and to be able to annotate places to replace throughout the `README.md` and `pom.xml` files.
This PR replaces the current `utilites/bump_versions.py` and `utilities/replace_versions.py` scripts in google-cloud-java so they can be used with other repositories like gax-java.
The workflow is now:
1. What type of release? (MINOR|patch|snapshot)
2. Bump versions.txt? (Y/n)
3. Update versions in pom.xml files? (Y/n)
4. Edit release notes
5. Create release branch? (Y/n)
6. Create PR? (Y/n)
See https://github.com/googleapis/google-cloud-java/issues/3777
This should make releasetool work for all of …
> Java: support multiple versions per release

- .kokoro/build.sh
- README.md
- releasetool/main.py
- releasetool/secrets.py
`releasetool reset` will delete the GitHub API key from keyring.
Closes #78.
> Add command to reset GitHub API key

- releasetool/commands/start/go.py
- releasetool/commands/start/java.py
- releasetool/commands/start/nodejs.py
- releasetool/commands/start/python.py
- releasetool/commands/start/ruby.py
- releasetool/commands/tag/java.py
- releasetool/commands/tag/nodejs.py
- releasetool/commands/tag/python.py
- releasetool/commands/tag/python_tool.py
- releasetool/commands/tag/ruby.py
- releasetool/github.py
This will allow autorelease to tag Python releases.
> Allow python-tool tag to be executed with external context.

- releasetool/commands/publish_reporter.py
This cuts down on the amount of configuration needed for release jobs.
> Let reporter figure out the github token location instead of needing to manually specify it

- .kokoro/release.sh
- MANIFEST.in
- releasetool/__main__.py
- releasetool/commands/publish_reporter.py
- releasetool/commands/publish_reporter.sh
- setup.py
This is used by release builds to easily report status without unnecessarily
duplicating this code all over the place.
> Add release reporter script.

- README.md
Also, format `releasetool tag` in a code block so that it's easier to see all the steps to run.
> Add steps for tagging the merged commit for the release

- README.md
- releasetool/commands/start/ruby.py
- releasetool/commands/tag/ruby.py
Allow autorelease to handle gemspecs that contain version directly rather than in version.rb
> prepare ruby for autorelease

- releasetool/commands/tag/ruby.py
Some ruby packages have underscores. e.g. `google-cloud-error_reporting`
> Allow underscores in package name

- README.md
Not all languages using releasetool have autorelease.
> Re-add manual `releasetool tag` instructions

- releasetool/commands/start/python.py
- tests/commands/start/test_python.py
Black prefers double-quotes, so this detects those as well as
single-quotes, preserving whatever was there.
> Make setup.py update robust to different quote marks

- releasetool/__main__.py
`releasetool start` will detect the correct language for standalone Python repositories.
> Detect language python when a directory src/google exists.

- releasetool/commands/tag/nodejs.py
- tests/commands/tag/test_nodejs.py
This PR updates the regex used to find the most recent CHANGELOG entry to support both our old-style manually generated CHANGELOG entries, and the [new templates](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits/templates) used for releases based on [conventionalcommits.org](https://conventionalcommits.org).
_I performed a tiny bit of refactoring so that we could test release note extraction in isolation._
> feat: add support for conventionalcommits.org CHANGELOG template

- releasetool/commands/tag/nodejs.py
`ctx` is populated by reference, we should not assign the return value of `_get_latest_release_notes`, which is `None`.
> fix: ctx is populated by reference

- releasetool/commands/start/java.py
Support updating the version numbers in dependencies.properties. This is used by gax-java. (See https://github.com/googleapis/gax-java/pull/705)
> Java: support updating dependencies.properties

- releasetool/commands/start/ruby.py
- tests/commands/start/test_ruby.py
Add slash separator (`/`) to ensure match string represents entire package name, to fix a bug in which tags for other packages (ex: "google-cloud-spanner") were returned for the "google-cloud" package, since its name is a subset.
[fixes #182]
I ran this branch locally to produce googleapis/google-cloud-ruby#3282
> Fix Ruby start#determine_last_release

- releasetool/commands/start/ruby.py
- releasetool/git.py
When releasing more than one package, it's nice to be automatically returned to `master` branch to begin the next release. When things work correctly, there is nothing left to do in the release branch in Ruby after `start` completes.
> ruby: Add checkout_master() to finish of start

- releasetool/commands/tag/nodejs.py
- tests/commands/tag/test_nodejs.py
The regex for extracting a GitHub release was too greedy if the prior release was a patch, rather than breaking change or feature.
see: https://github.com/googleapis/release-please/issues/140
> fix: release extraction regex was not handling patch releases properly

- releasetool/commands/start/java.py
Fixes #137 
Sometimes you want manually fix a version in the versions.txt manifest. The java start command separates the version bumping from replacing the version tags in the source. This PR adds the ability to do a no-op version bump.
> Java: Allow user to skip version bumping

- releasetool/commands/start/java.py
Don't prompt for autorelease on snapshots
Default the prompt to true for autorelease
> Java: autorelease by default

- releasetool/commands/start/ruby.py
The stackdriver package [got the wrong version bump](https://github.com/googleapis/google-cloud-ruby/pull/3483), this PR fixes the problem, hopefully without regression (I tested manually against several google-cloud-* packages and it works fine.)
> Fix last release detection for non-cloud packages in Ruby

- releasetool/commands/start/python.py
- tests/commands/start/test_python.py
> fix: id correct Python release when package names overlap.

- releasetool/__main__.py
- releasetool/commands/tag/php.py
Mostly copied from Node's tag command. I removed the bits that trigger Kokoro jobs, as I believe that isn't required for PHP.
> Add releasetool tag for PHP.

- releasetool/commands/tag/java.py
- tests/commands/tag/test_java.py
release-please creates the branch: `release-vx.y.z`.
> Java: relax tag parsing rules from branch name

- releasetool/__main__.py
- releasetool/commands/tag/dotnet.py
Our current process is to create tags with a .NET program, which performs extra validation - and can apply multiple tags. We don't want to replicate all that logic in releasetool, so for the moment we'll just assume the releases to create are in the PR.
The process will become:
- Create release PR (that changes the version numbers)
- Merge the release PR
- Run a modified version of the existing .NET tool, that modifies the release PR instead of applying tags directly:
- Add the "autorelease: pending" label
- Modify the body of the PR to include the releases to tag
- A cron job will pick up the release PR and run "releasetool tag"
- releasetool will perform the actual tagging and kick off a kokoro build
- kokoro will find the tags on the specified commit and create the NuGet packages and …
> Support releasetool tag for dotnet

- releasetool/commands/tag/ruby.py
Releasetool appears to be having trouble releasing ruby-style. [Release PR](https://github.com/googleapis/ruby-style/pull/18)
```
Processing Release ruby-style 1.24.0: https://github.com/googleapis/ruby-style/pull/18
> Determining the release tag.
PR head ref is release-ruby-style-v1.24.0
Package name is ruby-style
Package version is 1.24.0
Release tag is ruby-style/v1.24.0
> Determining the package name and version from your release tag.
> Grabbing the release notes.
HTTPError('404 Client Error: Not Found for url: https://api.github.com/repos/googleapis/ruby-style/contents/ruby-style/CHANGELOG.md?ref=05de1cc920d459357cf5621b2f0b9fbc3a4801a2',)
```
If google-cloud-ruby is the only repo with multiple packages, I think this will be less error-prone.
> Tweak repo detection for google-cloud-ruby.

- releasetool/commands/start/python.py
The 'python' in the user's environment might not have 'setuptools' installed.
> fix(python): use current interpreter to find package name

- releasetool/commands/start/python.py
So releasetool doesn't make PRs that the linter doesn't like. :)
> fix(python): use conventional commit format for PR title and commit

- releasetool/commands/start/go.py
- releasetool/commands/start/nodejs.py
- releasetool/commands/start/python.py
- releasetool/commands/start/ruby.py
Adds the version override dialog already in Java to `releasetool start` in the other languages.
https://github.com/googleapis/releasetool/blob/51ee1b50bc1023f209765b8ef21ab578989a6454/releasetool/commands/start/java.py#L308-L322
Closes #153
> fix: allow first version override

- releasetool/commands/publish_reporter.py
- releasetool/commands/tag/nodejs.py
I think this is a better place to implement the ignore logic I needed, rather than `autorelease`, as I still wanted to kick off the `docs` job.
This PR, instead of ignoring a repo completely, uses `releasetool` for tagging and doc publication, but allows a GitHub app to perform publication for configured repos.
> feat: allow doc publication without package publication

- releasetool/commands/tag/ruby.py
Ruby needs to release gem names with numerals .
> fix: allow numerals in Ruby gem names

- releasetool/commands/tag/nodejs.py
I'm using the GitHub app for publishing new libraries, skipping the step required to add a library to keystore.
> build: nodejs-recommender uses GitHub app for publication

- releasetool/commands/tag/nodejs.py
all new libraries are starting to use the publish-bot tool; autorelease is still used for kicking off doc publication.
> chore: billing budges publication is managed by publish bot

- releasetool/commands/tag/python.py
The f-string combined with the raw string wasn't working properly. This glues the version # in with string concatenation instead.
> fix(python): fix python changelog detection regex

- releasetool/commands/tag/nodejs.py
we are using the new publication tooling for this repo.
> chore: nodejs-monitoring-dashboards is handled by wombat

- releasetool/commands/tag/nodejs.py
This adds the googleapis/nodejs-game-servers client library to release-tool
> feat: adds Game Servers Node.js library

- releasetool/__main__.py
- releasetool/commands/publish_reporter.py
- releasetool/commands/tag/nodejs.py
I believe this will let us fully swap over to using a GitHub application + wombat dressing room for publication to npm (rather than doing it for a few select libraries).
Should be landed at same time as https://github.com/googleapis/synthtool/pull/425
_I admit I'm procrastinating._
> feat: move all node.js libraries to GitHub app for publication

- releasetool/commands/publish_reporter.py
- releasetool/commands/tag/nodejs.py
In the short term, I believe we might need to use kokoro-based publication for (which is bumping into memory constraint issues compiling in cloud functions).
> fix(publish): google-api-nodejs-client is hitting memory constraints

- releasetool/commands/common.py
- releasetool/commands/publish_reporter.py
- releasetool/commands/start/go.py
- releasetool/commands/start/java.py
- releasetool/commands/start/nodejs.py
- releasetool/commands/start/python.py
- releasetool/commands/start/python_tool.py
- releasetool/commands/start/ruby.py
- releasetool/commands/tag/dotnet.py
- releasetool/commands/tag/java.py
- releasetool/commands/tag/nodejs.py
- releasetool/commands/tag/php.py
- releasetool/commands/tag/python.py
- releasetool/commands/tag/python_tool.py
- releasetool/commands/tag/ruby.py
This caused a problem with a PR with a title of "Release Firestore libraries version 2.0.0"
> fix: Don't match names with spaces in for .NET packages

- releasetool/commands/tag/python.py
- releasetool/commands/tag/python_tool.py
Fixes #243.
Also removes the logic for the monorepo `google-cloud-python` as it is obsolete.
> fix(python): fix regex for release notes and remove monorepo logic

- releasetool/commands/tag/nodejs.py
Using a cloud function for publication is failing on some APIs.
> build: use kokoro for publishing logging

- .gitignore
- releasetool/__main__.py
- releasetool/commands/common.py
- releasetool/commands/publish_reporter.py
- releasetool/commands/publish_reporter.sh
- releasetool/github.py
- setup.py
This PR assumes that we will set three secrets:
* `APP_ID`: path to a file that contains a GitHub application ID.
* `INSTALLATION`: path to a file that contains an installation ID.
*  `GITHUB_PRIVATE_KEY`:  path to a file that contains the PEM secret for a GitHub application.
If these environments are found set, then rather than using magic-proxy, it grabs a JWT for our application and uses it to authenticate.
_Note: I'm not sure of a great way to write tests for this, but I've done an end to end testing, and confirmed the approach works._
> feat: add support for GitHub  JWT auth

- releasetool/commands/tag/nodejs.py
We continue to have bad luck with the GCF function Node.js was using for publication, for instance it likes to run out of memory for some publications.
Let's move back to kokoro, and call this  a failed experiment.
> fix(nodejs): move back to autorelease for publishes

- releasetool/commands/publish_reporter.py
- tests/test_publish_reporter.py
During refactor accidentally left reference to GitHub token, rather than github_token_raw.
> fix: referenced github_token rather than github_token_raw

- releasetool/commands/start/ruby.py
The large diff text is causing problems when creating a pull request. GitHub is kicking back an error for some reason, possibly due to size or some syntax in the diff.
> fix(ruby): Cut problematic text from release PR body

- releasetool/commands/tag/dotnet.py
We assume only the repo name matters, not the organization: the
kokoro job path does not contain the organization.
> feat: Allow the .NET autorelease process to work across multiple repositories

- .kokoro/release/release.cfg
@busunkim96 I'm seeing the error in logs:
```bash
[18:08:00][ERROR] Failed to get build config
com.google.devtools.kokoro.config.ConfigException: Neither the Build file nor the Cloud build local config have been specified
at com.google.devtools.kokoro.config.factory.BuilderPluginFactory.createBatchBuilder(BuilderPluginFactory.java:143)
at com.google.devtools.kokoro.config.factory.BuilderPluginFactory.from(BuilderPluginFactory.java:72)
at com.google.devtools.kokoro.jenkins.plugin.kokorojob.KokoroBuildConfig$Builder.buildWith(KokoroBuildConfig.java:83)
at com.google.devtools.kokoro.jenkins.plugin.kokorojob.store.ConfigStore.getKokoroBuildConfig(ConfigStore.java:120)
```
I was wondering if it's because we don't read the top level common.cfg, where these files are defined? 
CC: @jskeet.
> build: updates to config

- .kokoro/populate-secrets.sh
- .kokoro/release.sh
- .kokoro/release/common.cfg
- .kokoro/release/release.cfg
I've confirmed that the release build succeeds by building off my branch.
This switches releasetool publishing to the PyPI account `gcloudpypi`. I added the secret to secret manager.
> build: use gcloudpypi account for release

- releasetool/commands/tag/nodejs.py
I think this regex can just drop the `?`.
> fix(nodejs): semver digits are not optional

- releasetool/github.py
mypy is flagging a type issue, causing CI to fail in #294 and #295 . I think this should fix the issue. There's a spurious method being called on the encoded JWT (a string). I'm pretty sure the string can be set in the header as-is.
Requesting review from @bcoe because this was your code from #262 and I want to make sure there isn't something I'm missing.
> fix: Remove spurious method call when exchanging JWT for an access token

- releasetool/commands/tag/ruby.py
The Ruby apiary library is being broken out into separate libraries per service, along with separate core and generator libraries. As a result, the Ruby Apiary monorepo now contains multiple packages, each in a subdirectory.
This PR updates the Ruby release tagging logic to support this restructuring.
* Update the code that finds changelogs to look in the appropriate subdirectory.
* Update the code that determines which kokoro release job to trigger.
See internal cl/349793870
> feat(ruby): Support releases of split ruby apiary packages

- .kokoro-autorelease/build.sh
- .kokoro-autorelease/common.cfg
Currently, we're running the autorelease job directly on the Kokoro VM. Permissions can be wonky and it's hard to control installed versions.
This allows us to control the runtime environment by using Docker images that we maintain.
> build: use trampoline/docker for autorelease job

- autorelease/__main__.py
- autorelease/tag.py
- releasetool/commands/common.py
- releasetool/commands/tag/java.py
Delegate tagging to release-please for Java. This is needed to unblock Java release tagging which has gotten more complicated to support multiple release branches.
A more robust design to support all languages is forthcoming.
> fix(java): use release-please for java tagging

- releasetool/commands/tag/java.py
If release-please fails, autorelease tries to log the failing command
> fix(java): use token file for release-please

- autorelease/github.py
- autorelease/tag.py
I've done a healthy amount of QA, and switching to the search endpoint seems promising.
The API is described [here](https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests).
Queries end up looking something like this:
```curl
curl https://api.github.com/search/issues?q=org:googleapis+state:closed+label:%22autorelease%3A%20pending%22
```
Fixes #307
> fix: switch to using search API for finding merged release PRs

- releasetool/commands/common.py
- releasetool/commands/tag/nodejs.py
We should defer to the manifest releaser for creating CHANGELOG, determining version/tag.
> fix(manifest): defer to manifest releaser for version/CHANGELOG

- releasetool/commands/tag/ruby.py
- tests/commands/tag/test_tag_ruby.py
Ruby is reworking its release jobs for google-cloud-ruby. From this point, there will be a single release job shared by all libraries in the monorepo.
Please coordinate with dazuma internally before releasing.
> fix(ruby): Trigger new Ruby release job from google-cloud-ruby

- autorelease/trigger.py
This is part of go/deprecate-autorelease-tag where we switch from autorelease tagging to release-please tagging.
This will all autorelease to start triggering Kokoro off of `autorelease: tagged`
> fix(java): allow java builds in autorelease.trigger

- autorelease/trigger.py
Fixes #325 
This is the method for dynamic module loading used in the `tag` job - the `getattr` method looks cleaner, but is failing at runtime (but not test time?)
See https://github.com/googleapis/releasetool/pull/314#discussion_r620607966
> fix: revert to using importlib for dynamic module loading

- autorelease/trigger.py
- tests/test_autorelease_trigger.py
Fixes #330
This approach adds a label to the tagged release PR to indicate we have already triggered the release build. To retry for the next time, a maintainer can remove the `autorelease: triggered` label.
> fix: only trigger Kokoro jobs once

- setup.py
The published package on pypi is missing the report.xml.j2 file.
> fix: include jinja template in released package

- setup.py
The path doesn't include the package name.
Tested by doing an install from git in a docker container:
`git+git://github.com/chingor13/releasetool@fix-missing-template#egg=releasetool` and the installed package now has the jinja template available.
> fix: fix path in setup.py for template files

- autorelease/__main__.py
- autorelease/github.py
- autorelease/trigger.py
- tests/test_autorelease_trigger.py
This is an extra command to trigger a single release. The purpose of this command is to allow other mechanism for triggering the kokoro build without having to rewrite the proto2 -> pubsub logic.
> feat: add command for triggering a single kokoro job by PR url

- autorelease/tag.py
- autorelease/trigger.py
- tests/test_autorelease_tag.py
- tests/test_autorelease_trigger.py
They are migrated to release-please/release-trigger
Fixes #361
Fixes https://github.com/googleapis/repo-automation-bots/issues/2442
Fixes #343
Fixes #336
> fix: stop handling java repos

- autorelease/tag.py
- autorelease/trigger.py
After all repositories have been updated to use the release-trigger app, we can stop triggering nodejs jobs with the autorelease cron.
> fix(nodejs): stop autorelease for nodejs

- autorelease/trigger.py
This was causing the release-trigger bot to skip all jobs
Fixes #367
> fix: triggering a single release PR should not use the language allowlist

- .kokoro-autorelease/common.cfg
- .kokoro-autorelease/tag.cfg
- .kokoro-autorelease/trigger.cfg
It should be enough to remove the `backend_type` for now, this is how Node.js has their `keystore_resource` configured and tests are not failing.
@chingor13 has put work in to retire this repository, anyone on `release-please` will eventually be able to migrate away from `releasetool`. tldr; I'm tempted to hold off on retiring these secrets, in favor of retiring this repo next quarter.
Refs: #369
> build: remove deprecated backend_type config

- requirements.txt
git:// protocol seems to be deprecated.
see: https://github.blog/2021-09-01-improving-git-protocol-security-github/
> build: try to fix python install from GitHub

- autorelease/tag.py
PHP is using release-please for tagging releases
python_tool is no longer used (synthtool does not create releases)
> fix: stop running autorelease tag for php and python_tool

- releasetool/commands/tag/dotnet.py
- tests/commands/tag/test_tag_dotnet.py
`release-trigger` is currently unable to trigger dotnet release jobs as it does not know how to build the Kokoro release job name given the repository name.
Example from the logs:
```
Processing chore(main): release Google.CloudEvents.Protobuf 1.2.0: https://github.com/googleapis/google-cloudevents-dotnet/pull/126
No Kokoro job for https://github.com/googleapis/google-cloudevents-dotnet/pull/126, skipping.
```
> fix: implement kokoro_job_name helper for dotnet

- releasetool/commands/tag/java.py
- tests/test_autorelease_trigger.py
https://github.com/GoogleCloudPlatform/functions-framework-java has three different packages which use different kokoro jobs. Adding the configuration for the same
> fix: Configure kokoro jobs for functions-framework-java release 

- noxfile.py
- releasetool/commands/tag/ruby.py
- tests/commands/tag/test_tag_ruby.py
The ruby-spanner-activerecord release attempted to trigger a release of the ruby-spanner job because the name included `ruby-spanner`
> fix(ruby): check repo name exact match

- releasetool/commands/tag/java.py
This PR specifies the kokoro release job location for [spring-cloud-gcp](https://github.com/GoogleCloudPlatform/spring-cloud-gcp) and [cloud-spanner-r2dbc](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc).
This is a part of migrating the release process for these repos to release-please+release-trigger automation.
> fix(java): Specifying kokoro release job location for cloud java repositories

- requirements.txt
Reverts googleapis/releasetool#466
This is breaking publication:
```
ERROR: Could not find a version that satisfies the requirement packaging==22.0 (from versions: 14.0, 14.1, 14.2, 14.3, 14.4, 14.5, 15.0, 15.1, 15.2, 15.3, 16.0, 16.1, 16.2, 16.3, 16.4, 16.5, 16.6, 16.7, 16.8, 17.0, 17.1, 18.0, 19.0, 19.1, 19.2, 20.0, 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21.0, 21.1, 21.2, 21.3)
ERROR: No matching distribution found for packaging==22.0
```
This is probably an runtime issue (maybe older version of python?) We'll revert for now
> Revert "chore(deps): update dependency packaging to v22"

- autorelease/common.py
add special case for cndb-client-testing-protos for determing release languages from proto to java.
> chore: add special case for release languages

- autorelease/tag.py
- releasetool/filehelpers.py
- tests/test_autorelease_tag.py
Previously, for repositories whose language was not in the allowlist, we would only skip the actual tagging logic, but would still try to remove labels. After this change, we will also only attempt to remove labels if the language is in the allowlist.
> fix: skip entire tag workflow for languages not in the allowlist

- autorelease/__main__.py
- autorelease/trigger.py
- releasetool/commands/tag/cpp.py
- tests/commands/tag/test_tag_cpp.py
- tests/test_autorelease_trigger.py
New variation on the trigger-single command:
--release: the github release uri
--lang: the language, so we don't have to guess
> feat: cpp support

- autorelease/tag.py
Ruby is migrating off of the Kokoro-based release tagger and trigger, and adopting the GitHub App bots. (See, e.g. https://github.com/googleapis/google-cloud-ruby/pull/21575 and corresponding pull requests across all Ruby repos.)
Please coordinate with @dazuma for merging. We want this merged and released about the same time as the corresponding Ruby repo PRs are merged.
> feat: Remove Ruby from Kokoro tagger

- releasetool/commands/tag/ruby.py
Switches the kokoro release job for google-cloudevents-ruby from one located in the `cloud-devrel/ruby` directory to one located `cloud-devrel/client-libraries` directory. (The kokoro configs have already been duplicated into the new location.) This move is an attempt to provide the correct GitHub credentials for the release job to update the release pull request. The client-libraries directory has access to resources for repositories under the googleapis org, resources that seem not to be available to other subdirectories of cloud-devrel.
> fix: update kokoro release job name for google-cloudevents-ruby

- releasetool/commands/tag/java.py
In this PR:
- Specify kokoro release job for appengine-plugins
Repository https://github.com/GoogleCloudPlatform/appengine-plugins/
Kokoro job: prod:appengine-plugins-core/gcp_ubuntu/stage
> feat: add appengine-plugins to repo list

- releasetool/commands/common.py
Example: `https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod%3Afoo%2Fbar%2Fautorelease` -> `https://fusion2.corp.google.com/ci;prev=s/kokoro/prod:foo%2Fbar%2Fautorelease`
> fix: update fusion url to fusion2

- releasetool/commands/tag/dotnet.py
This isn't an issue for normal automated releases, but has bitten us in the past when creating release PRs manually.
Fixes b/345375783
> fix: avoid tag failures for .NET on empty PR bodies

- releasetool/commands/tag/ruby.py
Add the ruby-core-libraries github repository to the configuration so release triggering knows how to find the release kokoro job.
> feat: support ruby-core-libraries repository

- autorelease/trigger.py
- noxfile.py
- tests/test_autorelease_trigger.py
For the languages that fully migrated to shared internal scripts, assume a multiScm name that is the repo name.
This makes it so every repository will not need to update the release-trigger.yml to set multiScmName.
> feat(autorelease): automatically assume multiScm for node and python

- releasetool/commands/tag/dotnet.py
We now have:
- Spanner EF from the new CI in Docker Pools
- Cloud Events from the new CI in Instance Pools, which is MOSS compliant.
- Everything else on old CI.
Once we have Instance Pools working, I'll migrate Spanner EF there and then everything else.
> feat: Support releasing .NET from the Cloud SDK Windows Kokoro Instance.

- autorelease/tag.py
Remove `dotnet` from language allowlist as release-please is now doing the tagging and all repos under dotnet have been migrated to use this. Since we are doing this, we no longer need the explicit deny list for individual repos.
> chore: Remove dotnet from language allowlist
